package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"inverse.so/engine/collections"
	"inverse.so/engine/onboarding"
	"inverse.so/graph/model"
	"inverse.so/internal"
	"inverse.so/internal/customError"
	"inverse.so/structure"
)

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.NewCollection) (*model.Collection, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return collections.CreateCollection(&input, authenticationDetails)
}

// RegisterInverseUsername is the resolver for the registerInverseUsername field.
func (r *mutationResolver) RegisterInverseUsername(ctx context.Context, input model.NewUsernameRegisgration) (*model.CreatorDetails, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return onboarding.RegisterInverseUsername(authenticationDetails.Address, &input)
}

// GetCreatorDetails is the resolver for the getCreatorDetails field.
func (r *queryResolver) GetCreatorDetails(ctx context.Context) (*model.CreatorDetails, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	creatorInfo, err := onboarding.CreateCreatorProfileIfAddressIsMissing(authenticationDetails.Address)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return creatorInfo.ToGraphData(), nil
}

// GetOnboardinProgress is the resolver for the getOnboardinProgress field.
func (r *queryResolver) GetOnboardinProgress(ctx context.Context) (*model.OnboardingProgress, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	onbaordingInfo, err := onboarding.GetOnboardinProgress(authenticationDetails.Address)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return onbaordingInfo, nil
}

// IsInverseNameIsAvailable is the resolver for the isInverseNameIsAvailable field.
func (r *queryResolver) IsInverseNameIsAvailable(ctx context.Context, input model.NewUsernameRegisgration) (bool, error) {
	return onboarding.CheckIfInverseNameIsAvailable(&input)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) CheckIfInverseNameIsAvailable(ctx context.Context, input model.NewUsernameRegisgration) (bool, error) {
	panic(fmt.Errorf("not implemented: CheckIfInverseNameIsAvailable - checkIfInverseNameIsAvailable"))
}
