package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"inverse.so/engine/aiimages"
	"inverse.so/engine/collections"
	"inverse.so/engine/items"
	"inverse.so/engine/onboarding"
	"inverse.so/engine/whitelist"
	"inverse.so/graph/model"
	"inverse.so/internal"
	"inverse.so/internal/customError"
	"inverse.so/services"
	"inverse.so/structure"
)

// Items is the resolver for the items field.
func (r *collectionResolver) Items(ctx context.Context, obj *model.Collection) ([]*model.Item, error) {
	return items.FetchCollectionItems(obj.ID, nil)
}

// Creator is the resolver for the creator field.
func (r *itemResolver) Creator(ctx context.Context, obj *model.Item) (*model.CreatorDetails, error) {
	return onboarding.FetchItemCreatorByCollectionId(obj.CollectionID)
}

// AuthorizedSubdomains is the resolver for the authorizedSubdomains field.
func (r *itemResolver) AuthorizedSubdomains(ctx context.Context, obj *model.Item) ([]string, error) {
	return items.FetchAuthotizedSubdomainsForItem(obj.ID)
}

// RegisterInverseUsername is the resolver for the registerInverseUsername field.
func (r *mutationResolver) RegisterInverseUsername(ctx context.Context, input model.NewUsernameRegisgration) (*model.CreatorDetails, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return onboarding.RegisterInverseUsername(authenticationDetails.Address, &input)
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CollectionInput) (*model.Collection, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return collections.CreateCollection(&input, authenticationDetails)
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, collectionID string, input model.CollectionInput) (*model.Collection, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return collections.UpdateCollection(collectionID, &input, authenticationDetails)
}

// CreateItem is the resolver for the createItem field.
func (r *mutationResolver) CreateItem(ctx context.Context, input model.ItemInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return items.CreateItem(&input, authenticationDetails)
}

// UpdateItem is the resolver for the updateItem field.
func (r *mutationResolver) UpdateItem(ctx context.Context, itemID string, input model.ItemInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return items.UpdateItem(itemID, &input, authenticationDetails)
}

// CreateEmailWhitelistForItem is the resolver for the createEmailWhitelistForItem field.
func (r *mutationResolver) CreateEmailWhitelistForItem(ctx context.Context, input model.NewEmailWhitelistInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return whitelist.CreateEmailWhitelistForItem(&input, authenticationDetails)
}

// CreateEmailDomainWhitelist is the resolver for the createEmailDomainWhitelist field.
func (r *mutationResolver) CreateEmailDomainWhitelist(ctx context.Context, input model.NewEmailDomainWhitelistInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return whitelist.CreateEmailDomainWhitelist(&input, authenticationDetails)
}

// CreateTwitterCriteriaForItem is the resolver for the createTwitterCriteriaForItem field.
func (r *mutationResolver) CreateTwitterCriteriaForItem(ctx context.Context, input model.NewTwitterCriteriaInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return whitelist.CreateTwitterCriteria(input, authenticationDetails)
}

// CreateTelegramCriteriaForItem is the resolver for the createTelegramCriteriaForItem field.
func (r *mutationResolver) CreateTelegramCriteriaForItem(ctx context.Context, input model.NewTelegramCriteriaInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return whitelist.CreateTelegramCriteria(input, authenticationDetails)
}

// CreatePatreonCriteriaForItem is the resolver for the createPatreonCriteriaForItem field.
func (r *mutationResolver) CreatePatreonCriteriaForItem(ctx context.Context, input model.NewPatreonCriteriaInput) (*model.Item, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return whitelist.CreatePatreonCriteria(input, authenticationDetails)
}

// ValidateTwitterCriteriaForItem is the resolver for the validateTwitterCriteriaForItem field.
func (r *mutationResolver) ValidateTwitterCriteriaForItem(ctx context.Context, itemID string, authID *string) (bool, error) {
	if authID == nil {
		return false, customError.ErrToGraphQLError(structure.InverseInternalError, "authID is required", ctx)
	}

	return whitelist.ValidateTwitterCriteriaForItem(itemID, *authID)
}

// ValidateTelegramCriteriaForItem is the resolver for the validateTelegramCriteriaForItem field.
func (r *mutationResolver) ValidateTelegramCriteriaForItem(ctx context.Context, itemID string, authID *string) (bool, error) {
	if authID == nil {
		return false, customError.ErrToGraphQLError(structure.InverseInternalError, "authID is required", ctx)
	}

	return whitelist.ValidateTelegramClaimCriteria(itemID, *authID)
}

// ValidatePatreonCriteriaForItem is the resolver for the validatePatreonCriteriaForItem field.
func (r *mutationResolver) ValidatePatreonCriteriaForItem(ctx context.Context, itemID string, authID *string) (bool, error) {
	if authID == nil {
		return false, customError.ErrToGraphQLError(structure.InverseInternalError, "authID is required", ctx)
	}

	return whitelist.ValidatePatreonCriteriaForItem(itemID, authID)
}

// StartEmailVerificationForClaim is the resolver for the startEmailVerificationForClaim field.
func (r *mutationResolver) StartEmailVerificationForClaim(ctx context.Context, input model.EmailClaimInput) (*model.StartEmailVerificationResponse, error) {
	return whitelist.StartEmailVerificationForClaim(&input)
}

// CompleteEmailVerificationForClaim is the resolver for the completeEmailVerificationForClaim field.
func (r *mutationResolver) CompleteEmailVerificationForClaim(ctx context.Context, input model.CompleteEmailVerificationInput) (*model.CompleteEmailVerificationResponse, error) {
	return whitelist.CompleteEmailVerificationForClaim(&input)
}

// GenerateSignatureForClaim is the resolver for the generateSignatureForClaim field.
func (r *mutationResolver) GenerateSignatureForClaim(ctx context.Context, input model.GenerateClaimSignatureInput) (*model.MintAuthorizationResponse, error) {
	return whitelist.GenerateSignatureForClaim(&input)
}

// StoreSignerInfo is the resolver for the storeSignerInfo field.
func (r *mutationResolver) StoreSignerInfo(ctx context.Context, input model.SignerInfo) (bool, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return false, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return onboarding.StoreUserAccountSignerAddress(input, authenticationDetails)
}

// GetCreatorDetails is the resolver for the getCreatorDetails field.
func (r *queryResolver) GetCreatorDetails(ctx context.Context) (*model.CreatorDetails, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	creatorInfo, err := onboarding.CreateCreatorProfileIfAddressIsMissing(authenticationDetails.Address)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}
	// 28,500 -
	// The hub karen ( )
	//

	return creatorInfo.ToGraphData(), nil
}

// GetOnboardinProgress is the resolver for the getOnboardinProgress field.
func (r *queryResolver) GetOnboardinProgress(ctx context.Context) (*model.OnboardingProgress, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	onbaordingInfo, err := onboarding.GetOnboardinProgress(authenticationDetails.Address)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return onbaordingInfo, nil
}

// IsInverseNameIsAvailable is the resolver for the isInverseNameIsAvailable field.
func (r *queryResolver) IsInverseNameIsAvailable(ctx context.Context, input model.NewUsernameRegisgration) (bool, error) {
	return onboarding.CheckIfInverseNameIsAvailable(&input)
}

// FetchCollectionByID is the resolver for the fetchCollectionById field.
func (r *queryResolver) FetchCollectionByID(ctx context.Context, collectionID string) (*model.Collection, error) {
	return collections.FetchCollectionByID(collectionID)
}

// FetchCreatorCollections is the resolver for the fetchCreatorCollections field.
func (r *queryResolver) FetchCreatorCollections(ctx context.Context) ([]*model.Collection, error) {
	authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	if err != nil {
		return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	}

	return collections.FetchCreatorCollections(authenticationDetails)
}

// FetchItemsInCollection is the resolver for the fetchItemsInCollection field.
func (r *queryResolver) FetchItemsInCollection(ctx context.Context, collectionID string) ([]*model.Item, error) {
	// authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	// if err != nil {
	// 	return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	// }

	return items.FetchCollectionItems(collectionID, nil)
}

// FetchItemByID is the resolver for the fetchItemById field.
func (r *queryResolver) FetchItemByID(ctx context.Context, itemID string) (*model.Item, error) {
	return items.FetchItemByID(itemID)
}

// GetImageSuggestions is the resolver for the getImageSuggestions field.
func (r *queryResolver) GetImageSuggestions(ctx context.Context, prompt string, preset *model.AiImageStyle) ([]*model.ImageResponse, error) {
	// authenticationDetails, err := internal.GetAuthDetailsFromContext(ctx)
	// if err != nil {
	// 	return nil, customError.ErrToGraphQLError(structure.InverseInternalError, err.Error(), ctx)
	// }
	return aiimages.GetImageSuggestions(prompt, preset)
}

// GetTweetDetails is the resolver for the getTweetDetails field.
func (r *queryResolver) GetTweetDetails(ctx context.Context, tweetLink string) (*model.TweetDetails, error) {
	return services.FetchTweetDetails(tweetLink)
}

// GetTwitterUserDetails is the resolver for the getTwitterUserDetails field.
func (r *queryResolver) GetTwitterUserDetails(ctx context.Context, userName string) (*model.UserDetails, error) {
	return services.FetchUserDetails(userName)
}

// Collection returns CollectionResolver implementation.
func (r *Resolver) Collection() CollectionResolver { return &collectionResolver{r} }

// Item returns ItemResolver implementation.
func (r *Resolver) Item() ItemResolver { return &itemResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type collectionResolver struct{ *Resolver }
type itemResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) GetUserDetails(ctx context.Context, userName string) (*model.UserDetails, error) {
	return services.FetchUserDetails(userName)
}
func (r *queryResolver) GetTwitterFollowersCount(ctx context.Context, profileLink string) (int, error) {
	panic(fmt.Errorf("not implemented: GetTwitterFollowersCount - getTwitterFollowersCount"))
}
func (r *itemResolver) Interaction(ctx context.Context, obj *model.Item) ([]*model.InteractionType, error) {
	panic(fmt.Errorf("not implemented: Interaction - interaction"))
}
