// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID          string  `json:"ID"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	Thumbnail   string  `json:"thumbnail"`
	Items       []*Item `json:"items"`
}

type CollectionInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Thumbnail   *string `json:"thumbnail,omitempty"`
}

type CreatorDetails struct {
	CreatorID       string  `json:"creatorID"`
	Address         string  `json:"address"`
	InverseUsername *string `json:"inverseUsername,omitempty"`
}

type Item struct {
	ID           string `json:"ID"`
	Name         string `json:"name"`
	Image        string `json:"image"`
	Description  string `json:"description"`
	CollectionID string `json:"collectionId"`
}

type ItemInput struct {
	Name         *string `json:"name,omitempty"`
	Image        *string `json:"image,omitempty"`
	Description  *string `json:"description,omitempty"`
	CollectionID *string `json:"collectionID,omitempty"`
}

type NewUsernameRegisgration struct {
	InverseUsername string `json:"inverseUsername"`
}

type OnboardingProgress struct {
	RegisterdInverseUsername bool `json:"registerdInverseUsername"`
}
