// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID         string `json:"ID"`
	Name       string `json:"name"`
	ContentURI string `json:"contentURI"`
}

type CreatorDetails struct {
	CreatorID string `json:"creatorID"`
	Address   string `json:"address"`
}

type NewCollection struct {
	Name       string `json:"name"`
	ContentURI string `json:"contentURI"`
}
